#!/bin/sh

inet4_data=`/sbin/ifconfig eth0 | grep inet | head -1 --`
raw_ip_address=`echo $inet4_data | cut -d: -f 2 | cut -dB -f 1`
ip_address=`echo $raw_ip_address | sed 's/^[ ]//g'`

echo $ip_address
